// ─── Common ───────────────────────────────────────────────────────────────────
export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
}

export interface ApiError {
  statusCode: number;
  message: string;
  code?: string;
}

// ─── Auth DTOs ────────────────────────────────────────────────────────────────
export interface LoginDto {
  email: string;
  password: string;
}

export interface LoginResponseDto {
  accessToken: string;
  user: {
    id: string;
    email: string;
    fullName: string;
    roles: string[];
  };
}

export interface JwtPayload {
  sub: string;       // user_id
  roles: string[];
  iat: number;
  exp: number;
}

export interface RefreshTokenPayload {
  sub: string;
  jti: string;
  exp: number;
}

// ─── Workshop DTOs ────────────────────────────────────────────────────────────
export interface CreateWorkshopDto {
  title: string;
  speakerName: string;
  roomName: string;
  roomMapUrl?: string;
  capacity: number;
  feeType: 'FREE' | 'PAID';
  price?: number;
  startsAt: string; // ISO 8601
  endsAt: string;
}

export interface UpdateWorkshopDto extends Partial<CreateWorkshopDto> {}

export interface WorkshopDto {
  id: string;
  title: string;
  speakerName: string;
  roomName: string;
  roomMapUrl?: string;
  capacity: number;
  confirmedCount: number;
  heldCount: number;
  feeType: string;
  price?: number;
  startsAt: string;
  endsAt: string;
  status: string;
  summaryStatus: string;
  aiSummary?: string;
}

export interface WorkshopStatsDto {
  totalRegistrations: number;
  confirmedCount: number;
  pendingPaymentCount: number;
  checkinCount: number;
  utilizationPct: number;
}

// ─── Registration DTOs ────────────────────────────────────────────────────────
export interface CreateRegistrationDto {
  workshopId: string;
  idempotencyKey: string;
  queueToken?: string;
}

export interface RegistrationDto {
  id: string;
  workshopId: string;
  status: string;
  holdExpiresAt?: string;
  createdAt: string;
}

export interface SeatUpdateEvent {
  workshopId: string;
  remainingSeats: number;
  heldCount: number;
  confirmedCount: number;
}

// ─── Payment DTOs ─────────────────────────────────────────────────────────────
export interface PaymentIntentDto {
  paymentIntentId: string;
  paymentUrl: string;
  amount: number;
}

// ─── Check-in DTOs ────────────────────────────────────────────────────────────
export interface CheckinEventDto {
  eventId: string;       // UUID generated by PWA
  registrationId: string;
  workshopId: string;
  deviceId: string;
  scannedAt: string;     // ISO 8601
}

export interface CheckinSyncResultDto {
  eventId: string;
  status: 'ACCEPTED' | 'DUPLICATE' | 'INVALID';
  reason?: string;
}

export interface PreloadRosterDto {
  workshopId: string;
  hmacSecret: string;
  roster: {
    registrationId: string;
    studentId: string;
    qrTokenHash: string;
  }[];
}

// ─── Notification DTOs ────────────────────────────────────────────────────────
export interface NotificationDto {
  id: string;
  eventType: string;
  payload: Record<string, unknown>;
  status: string;
  createdAt: string;
  read: boolean;
}

// ─── Import DTOs ──────────────────────────────────────────────────────────────
export interface ImportBatchDto {
  id: string;
  filePath: string;
  status: string;
  totalRows: number;
  validRows: number;
  errorRows: number;
  startedAt?: string;
  completedAt?: string;
  createdAt: string;
}
